### ISSUE TITLE
Does officelive cache your documents?

### ISSUE THREAD

**Issue by hahatulk** [yatheeshraju/preview-office-docs#1]
When i once open document in officelive, it is avaliable to view without any authorization. How do i disable cache? My docs must be private

**Comment by hahatulk** [comment]
To authorize i provide token in query params when accessing documents

**Comment by yatheeshraju** [comment]
> To authorize i provide token in query params when accessing documents

can you provide a sample URL you are trying to access so I  can check it

**Comment by hahatulk** [comment]
> > To authorize i provide token in query params when accessing documents
> 
> can you provide a sample URL you are trying to access so I can check it

i cant, sorry. There is auth token.
But i can suggest to use google doc API, it does not cache documents and working the same. Good for private viewing. This is solution for my problem

API: https://docs.google.com/viewer?embedded=true&url=

**Comment by yatheeshraju** [comment]
@hahatulk will look into adding google docs as an option in future . Thanks for suggestions
